### ISSUE TITLE
Issue in localization of Time showing I18n::MissingTranslationData: translation missing: fr.time.formats.default

### ISSUE THREAD

**Issue by syeduzairshah** [ruby-i18n/i18n#284]
when I try to localize time using  `I18n.l(Time.zone.now)` I receive 

```
I18n::MissingTranslationData: translation missing: fr.time.formats.default
```

when I debugged gem I found  lookup function of simple.rb the output of result[:fr] instead of showing time format I defined in gem which was

```
fr:
  time:
    am: a.m.
    formats:
      default: '%a, %d %b %Y %H:%M:%S %z'
      long: '%B %d, %Y %H:%M'
      short: '%d %b %H:%M'
    pm: p.m.
```

showing 
time : Time

Can you guide me why it is showing like this 

Thanks
