### ISSUE TITLE
Translations returned as hash when model-inflection has nested keys

### ISSUE THREAD

**Issue by chevinbrown** [ruby-i18n/i18n#514]
## Pre 1.7.1 State
Related: https://github.com/ruby-i18n/i18n/issues/510

Our translations look something like:
```
activerecord:
  models:
    moose:
      one: Moose
      other: Moosen
      moose_types:
        big: Big ol moose
        ...
```
## What I expected to happen
`Moose.model_name.human(count: 2) #=> 'Moosen'`
## What actually happened
`Moose.model_name.human(count: 2) #=> Hash`
(_Actually_, I think this makes more sense!)

## Versions of i18n, rails, and anything else you think is necessary
- ruby 2.6
- rails 5.2
- i18n 1.8.1
----
So, it seems that our application wasn't really using model-translations idiomatically. The usage _are not attributes_, so they kinda got shoved in below the model-key.

If that pattern is considered wrong, this is a good forcing function towards convention (maybe it can be added to docs?). If it's an acceptable pattern, I would consider this a regression.

Happy to provide more detail/insight if required, but this seems pretty straightforward.

**Comment by radar** [comment]
The latest release of i18n is 1.8.2 and contains a fix for this issue: https://github.com/ruby-i18n/i18n/releases/tag/v1.8.2.

You’re saying you’re using 1.8.1.

**Comment by chevinbrown** [comment]
@radar sounds good. 

Would you say that the pattern of nesting attributes within a key meant for inflection is bad?

**Comment by radar** [comment]
Likely yes. It shouldn’t effect the performance of the library. It’s hash-based, so it’s only picking out the relevant keys as you need them. It’ll ignore other keys.

**Comment by chevinbrown** [comment]
That's kind of what I'm wondering...it may have been a regression, but if it forces better patterns, I'm for it. 👍 
In either case, thanks for being so responsive and helpful! 

❤️

**Comment by chevinbrown** [comment]
@radar can confirm this still caused the same issues in 1.8.2.

**Comment by radar** [comment]
I am unable to reproduce this in a new Rails application. Please provide an application that reliably reproduces the issue with any version of Rails, and I18n 1.8.2.

**Comment by mobilutz** [comment]
@chevinbrown Unfortunately, there is still in error in 1.8.2

When you use the following locale file content:
```YAML
en:
  model:
    one: Single
    other: Multiple
    nested:
      broken: Broken
```

Then you see the following situation:
```ruby
> I18n.t('model', count: 1)
{:one=>"Single", :other=>"Multiple", :nested=>{:broken=>"Broken"}}
```

When there is no nested information, so the `nested` part from the YAML is not there, then everything works.

```YAML
en:
  model:
    one: Single
    other: Multiple
```

```ruby
> I18n.t('model', count: 1)
Multiple
```

Do you want to have another issue for this?
