### ISSUE TITLE
Version 1.7 still marked as latest release in github

### ISSUE THREAD

**Issue by sergioisidoro** [ruby-i18n/i18n#518]
I'm wondering if this project uses github releases. 
https://github.com/ruby-i18n/i18n/releases

1.7 still appears as the latest release, which can cause some confusion. 
May I suggest the use of this action? - https://github.com/actions/create-release

```
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
```
