### ISSUE TITLE
[BUG] mongoid model error validations not working

### ISSUE THREAD

**Issue by pnock** [ruby-i18n/i18n#619]
## What I tried to do

We have things like this in our yml file for validation messages:

```
en:
  errors:
    messages:
      taken: "Message 1"
  mongoid:
    errors:
      models:
        user:
          attributes:
            name:
              blank: ...
              taken: "Message 2"
```
## What I expected to happen

Until V1.9.1, the "taken" validation error for our user model was "Message 2". 

## What actually happened

It doesn't seem to recognize the model specific validation messages, and we get "Message 1" instead.

## Versions of i18n, rails, and anything else you think is necessary

This changed after updating i18n gem from 1.8.11 to 1.9.1
