### ISSUE TITLE
Curious about what the maintainer thinks about this gist

### ISSUE THREAD

**Issue by martijnenco** [ruby-i18n/i18n#714]
Hello!

For an application I needed to add variations in my translation files, the way I see most people do it is creating just more locale files like `en_formal.yml` & `en_informal.yml`. I kinda find that very very ugly and not at all DRY. So that why I made this initializer that partly overrides this gem.

Here is the gist, with my code and explanation: [I18n Variations](https://gist.github.com/martijnenco/5082c7ff82514f08f8f735d0ac3e47bd)

TL:DR;
It's making this work:
```yaml
en:
  some_translation_that_does_not_have_variations: "Hello world, I say my greetings to everyone the same way!"
  some_translation_that_has_variations:
    formal: "I am being very polite here"
    informal: "I am not, deal with it."
```

If people maintainers think this is awesome or might be a good fight I would like to implement it to the gem.
