### ISSUE TITLE
translation returning hashes

### ISSUE THREAD

**Issue by asanghi** [ruby-i18n/i18n#95]
```
en:
  formtastic:
    author:
      name: Author Name
    post:
      title: Post's Title
```

It so happens that the lookup is made with the following defaults.

``` ruby
I18n.translate(:"post.new.author",{:defaults => [:"post.author",:author,""], :scope => [:formtastic, :labels]})
```

which returns

 `{:name => "Author Name"}`

Now, I can see a test that specs I18n returns a  hash when the lookup as such.

My instinct was that it would return a string or would raise an appropriate exception or return nil or blank if the key was not found. 

Can you please inform me of the usefulness of returning a hash when doing a translation?
